version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-5000}:${PORT_WEB_UI-5000}"
    # ports:
    #   - "4567-4597:4567-4597"
    #   - "${PORT_WEB_UI-5000}:${PORT_WEB_UI-5000}"
    environment:
      - SERVICES=s3,apigateway,lambda,sns,sqs
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI-5000}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
